/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.maria.adelaida.patino.ocampo.View.gui;


import com.maria.adelaida.patino.ocampo.Controller.ReportesController;
import com.maria.adelaida.patino.ocampo.View.gui.modeloui.ComprasTableModel;
import com.maria.adelaida.patino.ocampo.View.gui.modeloui.LideresTableModel;
import com.maria.adelaida.patino.ocampo.View.gui.modeloui.ProyectosTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;




/**
 *
 * @author maria
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    
    private  ReportesController controlador;
    
    public FrmPrincipal() {
        initComponents();
        
        setSize(800, 600);
        setLocationRelativeTo(null);
        
        this.controlador = new ReportesController();
        tablaLider.setModel(new LideresTableModel());
        tablaProyectos.setModel(new ProyectosTableModel());
        tablaCompras.setModel(new ComprasTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        InformeLideres = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLider = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProyectos = new javax.swing.JTable();
        InformeProyectos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        informeCompras = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informes Reto 5");
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Primer Informe"));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        InformeLideres.setText("Informe de Lideres");
        InformeLideres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeLideresActionPerformed(evt);
            }
        });
        jPanel1.add(InformeLideres, java.awt.BorderLayout.PAGE_END);

        jScrollPane3.setViewportView(tablaLider);

        jPanel1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Segundo Informe"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setViewportView(tablaProyectos);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        InformeProyectos.setText("Informacion Proyectos");
        InformeProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformeProyectosActionPerformed(evt);
            }
        });
        jPanel2.add(InformeProyectos, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tercer Informe"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(tablaCompras);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        informeCompras.setText("Informe Compras");
        informeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeComprasActionPerformed(evt);
            }
        });
        jPanel3.add(informeCompras, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InformeLideresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeLideresActionPerformed
        // Cargar datos 
        cargarListaLideres();
    }//GEN-LAST:event_InformeLideresActionPerformed

    private void InformeProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformeProyectosActionPerformed
        
        cargarListaProyectos();
    }//GEN-LAST:event_InformeProyectosActionPerformed

    private void informeComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeComprasActionPerformed
        cargarListaCompras();
    }//GEN-LAST:event_informeComprasActionPerformed

    private void cargarListaLideres(){
        try{
            var lideres = controlador.lideres();
            ((LideresTableModel)tablaLider.getModel()).setDatos(lideres);
            
            
        }catch (SQLException ex){
            mostrarError("Error cargando informe de proyectos", ex);
        }
    }
    
    private void cargarListaProyectos(){
        try{
            var proyectos = controlador.proyectos();
            ((ProyectosTableModel)tablaProyectos.getModel()).setDatos(proyectos);
            
            
        }catch (SQLException ex){
            mostrarError("Error cargando informe de proyectos", ex);
    }    
    } 
    
    private void cargarListaCompras(){
        try{
            var compras = controlador.compras();
            ((ComprasTableModel)tablaCompras.getModel()).setDatos(compras);
            
            
        }catch (SQLException ex){
            mostrarError("Error cargando informe de proyectos", ex);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InformeLideres;
    private javax.swing.JButton InformeProyectos;
    private javax.swing.JButton informeCompras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTable tablaLider;
    private javax.swing.JTable tablaProyectos;
    // End of variables declaration//GEN-END:variables

    private void mostrarError(String error, Exception ex) {
        JOptionPane.showMessageDialog(this, error + ": " + ex.getMessage(), "Informes", JOptionPane.ERROR_MESSAGE);
    }

    
}
